[project]
name = "gwemfish"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arviz",
    "astropy",
    "blackjax-nightly",
    "corner",
    "dvc-ssh",
    "helens",
    "ipykernel",
    "jaxtronomy",
    "jupyter",
    "ler",
    "matplotlib",
    "nbconvert",
    "nifty8",
    "numpy",
    "numpyro",
    "optax",
    "scienceplots",
    "scipy",
    "utax",
    # "herculens @ git+https://github.com/Herculens/herculens.git@27acb009ba622e614beb7a674298669e621d546d",
    "herculens @ git+https://github.com/Herculens/herculens.git",
    "utax @ git+https://github.com/aymgal/utax.git",
    "helens @ git+https://github.com/Herculens/helens",
    "arviz",
    "ipython>=9.9.0",
    # JAX: CPU on macOS, CUDA on Linux
    "jax[cpu]>=0.9.0; sys_platform == 'darwin'",
    "jax[cuda12]>=0.9.0; sys_platform == 'linux'",
    "joblib>=1.5.3",
    "nautilus-sampler",
    "autofit>=2026.6.30.644",
    "autolens>=2026.6.30.644",
    "pocomc>=1.2.6",
    "nessai>=0.15.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv]
required-environments = [
    "sys_platform == 'darwin' and platform_machine == 'arm64'",
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
    "sys_platform == 'linux' and platform_machine == 'aarch64'",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
